### ISSUE TITLE
Burps embedded browser is not working

### ISSUE THREAD

**Issue by Anthonymcqueen21** [PortSwigger/backslash-powered-scanner#20]
Hello PortSwigger i am having a on-going problem with my new operating system named Parrot. I am getting many errors when it comes to a sandbox issues here is an example of what kind of errors i am receiving. 

**"net.portswigger.devtools.client.a9: Refusing to start browser as your current configuration does not support running without sandbox" ???**

**Comment by albinowax** [comment]
This is the repository for Backlash Powered Scanner. To contact PortSwigger, please use https://portswigger.net/support

**Comment by dclxviclan** [comment]
I have this problem too on Kali Linux on Android with Burp Suite

**Comment by albinowax** [comment]
To contact PortSwigger, please use https://portswigger.net/support
