### ISSUE TITLE
On MacOS settings window pops up multiple times when using Help->Search

### ISSUE THREAD

**Issue by M1ch00** [PortSwigger/backslash-powered-scanner#22]
This extension adds only a top-level menu activator instead of creating a submenu. On MacOS it causes the item to activate and show the settings window if other menu is opened and mouse moved over the "Backslash" item or when any text is entered into the Help->Search function. When searching it switches focus to the popup  and shows additional popups with subsequent keystrokes which is pretty annoying.

**Comment by albinowax** [comment]
Thanks for this report! I actually fixed this a while ago but forgot to push it.

**Comment by albinowax** [comment]
I've released the fix now.
