### ISSUE TITLE
Support for JSON parameters

### ISSUE THREAD

**Issue by ghost** [PortSwigger/backslash-powered-scanner#24]
Great tool.

Will there be support for JSON endpoints. Scanning with the latest version of the scanner with Burp doesn't issue any request.

**Comment by albinowax** [comment]
If you use Burp's scan engine (IE right click-> do active scan) it should work fine. Integrated support for bulk scanning JSON might land at some point but it's not a short term priority.

**Comment by ghost** [comment]
Last question, will here be support of injecting a custom marker to scan with the scanner just like Turbo Intruder?

**Comment by albinowax** [comment]
You can do this currently by using 'Scan defined insertion points' in the Intruder, and disabling non-extension scanchecks.
