### ISSUE TITLE
can't install the extension on Burp Suite version 1.7.37

### ISSUE THREAD

**Issue by ayadim** [PortSwigger/backslash-powered-scanner#27]
Hi,

I can't install the extension on Burp Suite version 1.7.37 is there's any solution ? 

It says : "Requires a later version of Burp"

Regards

**Comment by Hannah-PortSwigger** [comment]
Hi

The minimum version of Burp to use Backslash Powered Scanner is v2023.10.3.

We'll take a look at getting the README on this repo updated with the latest requirements.
