### ISSUE TITLE
usage?

### ISSUE THREAD

**Issue by kirtixs** [PortSwigger/backslash-powered-scanner#9]
Hi, 

where exactly can I use or enable/disable this extension?

The best,
Simon

**Comment by albinowax** [comment]
You can install the extension via the BApp store. It's enabled/disabled via the Extensions pane. When enabled, it'll automatically run and generate results (which will appear alongside the other burp issues) whenever you launch an active scan.

**Comment by kirtixs** [comment]
Wow, thanks for the quick reply.
Wasn't quite sure if I had to enable something while actively scanning.

I wish you a lot of bugs :)

**Comment by 3la2kb** [comment]
HI,
I've done the same but i can't see any 'Backslash powered' requests in the logger++ tab when i run active scanner.

Best regards,
Alaa

**Comment by albinowax** [comment]
They show up as 'Extender' requests in Logger++

**Comment by sizar3x** [comment]
hlw sir,
i installed the extention successfully but i cant seee where the extention is it?

**Comment by albinowax** [comment]
You can install the extension via the BApp store. It's enabled/disabled via the Extensions pane. When enabled, it'll automatically run and generate results (which will appear alongside the other burp issues) *whenever you launch an active scan*.

You can open the configuration using the 'Backslash' menu on the top right: https://pbs.twimg.com/media/DV7axO4XcAE178o.jpg:large

**Comment by ShH01m3s** [comment]
Hello, guys! Is this extension fully working on MacOS only? When I install the extension on a Window machine, not only I extremely raaaaaaaaaaaaaaaarely see Backslash's report after active scan (even when scanning very buggy websites designed for CTFs, but I also fail to find a tab on the top right or left or anywhere else in the application to configure the probes or at least see them. Please help! Is there some tutorial available on the Internet? Burp is of version 2.1.03. Thanks

**Edit**: After several adding and removing on the Extension tab I managed to get the Backslash tab on the top pane.

**Comment by ShH01m3s** [comment]
After adding and removing the extension in Extender I've managed to get the Backslash tab on the top pane. Also, I personally found using Logger++ helpful in analyzing and watching the requests generated during scan.
